---
title: "Peat Depth Model: compare models"
params:
  params_fn: 
    input: file
    label: 'Select parameters to import (.rds)'
    value: "????"
output:
    html_notebook:
    html_document:
    df_print: paged

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = TRUE,
	warning = TRUE
)
```

--- 

## Introduction

This document compares peat depth model performance between different models and areas. 



### Table xx. combined metrics for each model run

```{r}
#compile metrics
metrics.combined <- data.frame(
  run = rundate,
  dat = dat %>% summarise(n_points = length(depth), depth_med = median(depth), 
                          depth_min = min(depth), depth_max = max(depth),
                          elev_min = min(elev), elev_max = max(elev),
                          slope_min = min(slope), slope_max = max(slope)), 
  cv = data.frame(bias.lm, rmse.lm, coverage.lm, interv.lm, bias.sm, rmse.sm, coverage.sm, interv.sm),
  prdr = data.frame(dataset = "predictors", n_points = ncell(predictors), depth_med = as.numeric(NA), 
            depth_min = as.numeric(NA), depth_max = as.numeric(NA),
            elev_min = minValue(predictors$elevation), elev_max = maxValue(predictors$elevation),
            slope_min = minValue(predictors$slope), slope_max = maxValue(predictors$slope)),
  mod = data.frame(model.geo[c(1, 2, 4, 5, 6)],
                   intercept = model.geo$beta[[1]],
                   covar1 = model.geo$beta[[2]],
                   covar2 = model.geo$beta[[3]], 
                   model.geo[c(11, 12, 15, 17, 18)])
)


#make tidy
metrics.combined <- metrics.combined %>% mutate_all(as.character) %>% gather(key = metric, value = value, -run); metrics.combined 
#add to csv record
ifelse(file.exists("../outputs/metrics_combined.csv"), 
       yes = write_csv(metrics.combined, "../outputs/metrics_combined.csv", col_names = F, append = T), 
       no = write_csv(metrics.combined, "../outputs/metrics_combined.csv", col_names = T, append = F))
```




##Compare model outputs

```{r}
#read in metrics from csv
model_metrics <- read_csv("../outputs/metrics_combined.csv")
```


```{r}
model_metrics_w <- model_metrics %>% spread(key = metric, value = value)
model_metrics_w
```

```{r}
ggplot(model_metrics_w, aes(x = cv.rmse.sm, y = cv.rmse.lm)) +
  geom_point(aes(colour = run)) +
  coord_equal() +
  expand_limits(x = 0, y = 0)


ggplot(model_metrics_w, aes(x = dat.n_points, y = cv.rmse.sm)) +
  geom_point(aes(colour = run))

```


















