---
title: "Peat Depth Model: Model Evaluation"
params:
  params_fn: 
    input: file
    label: 'Select parameters to import (.rds)'
    value: "../data/parameters_spade.rds"
  model_fn: 
    input: file
    label: 'Select model to import (.rds)'
    value: "../outputs/model.geo_spade_run_20200828-1503.rds"
  inputs_fn: 
    input: file
    label: 'Select input data to import (.rds)'
    value: "../outputs/input.data.gs_spade_run_20200828-1503.rds"
  parallel:
    input: checkbox
    label: 'Use multiple cores?'
    value: FALSE
  subset:
    input: checkbox
    label: 'Subset large dataset? (selects 10,000 observations at random for evaluation)'
    value: FALSE
output:
    html_document:
    html_notebook:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
source("rsquared_funs.R")
source("backtransform.R")
```

-------  

```{r}
## Introduction
#This script evaluates a model using ten-fold cross validation and produces evaluation metrics.  
# *  the suffix `.tf` means "transformed" and `.btf` means "back-transformed"

# When you're happy with the document, run the following command in the command line: 
#  rmarkdown::render(input = "../england/R/evaluate.Rmd", output_file = paste0("../england/outputs/eval_", parameters$area_abbr, "_", parameters$rundate))
```



```{r, echo=FALSE}
#import parameters from previous runs
parameters <- readRDS(file = params$params_fn)

# if you need to change any imported parameters, do it here, e.g.: 
  #parameters$existing_parameter <- newvalue
  #parameters$new_parameter <- value

parameters$tf <- "cbrt" #set which transformation was applied to the data in the model

# add new parameters from yaml header

parameters[names(params)] <- params


#store graphics params in case things go wrong
par.ori <- par() #save default plotting parameters

set.seed(4321)
```

```{r}
#pre-set which back-transformation to use

btf <- function(x) {
  backtransform(x = x, tf = parameters$tf)
}
```



area|run
----|----
*`r paste0(parameters$area_name, " (", parameters$area_abbr, ")")`* | *`r parameters$rundate`*

-------    



```{r}
#load packages
library(tidyverse)#
library(raster)
library(rgdal)
library(sp)
library(sf)
library(elevatr)
library(geoR)
library(gstat)
library(stars)
library(flextable)
library(doParallel)
library(foreach)
```

```{r}
# set up clusters for parallel computing
if(parameters$parallel){
  source("gstat.cv.par.R")
  source("krige.cv.spatial.par.R")
  cl <- makeCluster(10)
  registerDoParallel()
}
```

### Import model and data
```{r}
#import model and data

if(!exists("model.geo")){model.geo <- readRDS(parameters$model_fn)}
if(!exists("sp_depth")){sp_depth <- readRDS(parameters$inputs_fn)}

predictors <- raster::stack(parameters$elev_raster_fn, parameters$slope_raster_fn)
names(predictors) <- c("elevation", "slope")

#columns which identify the model run
run_tag <- data.frame(area_abbr = rep(parameters$area_abbr, nrow(sp_depth)), rundate = rep(parameters$rundate, nrow(sp_depth)))

# the data used to generate the model
dat_sp <- cbind(sp_depth, 
                parameters$area_abbr, parameters$rundate)
names(dat_sp) <- c(names(sp_depth), "area_abbr", "rundate")
dat_sp$id <- seq(1,nrow(sp_depth)) #add an index

#subset the data for testing 
if(parameters$subset){
subset.index <- sort(sample(1:nrow(dat_sp), size = 10000, replace = FALSE))
dat_sp <- dat_sp[subset.index,]
run_tag <- run_tag[subset.index,]
}
# summarise data and covariate space
prdr.summ <- data.frame(dataset = "predictors", n_points = ncell(predictors), depth_med = as.numeric(NA), 
            depth_min = as.numeric(NA), depth_max = as.numeric(NA),
            elev_min = minValue(predictors$elevation) %>% round(2), elev_max = maxValue(predictors$elevation) %>% round(2),
            slope_min = minValue(predictors$slope) %>% round(2), slope_max = maxValue(predictors$slope) %>% round(2))
obs.summ <- dat_sp@data %>% summarise(dataset = "observations extract", n_points = length(depth), depth_med = median(depth), 
                  depth_min = min(depth), depth_max = max(depth), elev_min = min(elev), elev_max = max(elev),
                  slope_min = min(slope), slope_max = max(slope))

inputs_summary <- rbind(prdr.summ, obs.summ) %>% data.frame() %>% 
  mutate_at(vars(elev_min:slope_max), funs(round, .args = list("digits" = 2)))
```


Model specification  

```{r, ft.align="left"}
flextable(
  data.frame(model_name = paste0(parameters$area_abbr, "_", parameters$rundate), model.geo[1:3])) %>% 
  set_caption(caption = "Table 1a. Model Specification") %>% 
  autofit() 
```

Input and predictor summary  


```{r, ft.align="left"}
flextable(inputs_summary) %>% set_caption(caption = "Table 1b. Summary statistics for input and prediction data") %>% 
  add_footer_lines(paste(parameters$area_name, parameters$rundate)) %>% 
  autofit()
```


### Ten-fold cross validation    

This analysis uses the `gstat` function `krige.cv()` to perform ten-fold cross validation


#### Cross validation of spatial model

```{r}
# run cross validation 
if (parameters$parallel) { # cross validation on multiple cores
  print(paste("cross validation using", length(cl), "clusters"))
  data <- dat_sp
  nfold <- 1:10
  fold <- sample(nfold, nrow(data), replace = TRUE)
  data$fold <- fold
  sm.cv.sp <- foreach(i=nfold, .combine = "rbind") %dopar% {
    cbind( 
      gstat::krige(formula = cbrt_depth ~ elev + slope, locations = data[data$fold != i, ], 
                   newdata = data[data$fold == i, ], model = model.geo),
      data[data$fold == i, ])
  } 
  sm.cv.sp$residual <- sm.cv.sp$cbrt_depth - sm.cv.sp$var1.pred 
  sm.cv.sp$zscore <- sm.cv.sp$residual/sqrt(sm.cv.sp$var1.var)
  sm.cv.sp <- sm.cv.sp[,c("id", "var1.pred", "var1.var", "cbrt_depth", "residual", "zscore", "fold")]
} else { # standard cross validation
  sm.cv.sp <- krige.cv(formula = cbrt_depth ~ elev + slope, 
                       locations = dat_sp,
                       model = model.geo, 
                       nfold=10, verbose = FALSE)
  sm.cv.sp@proj4string <- dat_sp@proj4string
  sm.cv.sp <- cbind(sm.cv.sp, dat_sp)
  sm.cv.sp <- sm.cv.sp[,c("id", "var1.pred", "var1.var", "cbrt_depth", "residual", "zscore", "fold")]
}

names(sm.cv.sp) <- c("id", "pred.tf", "var", "obs.tf", "resid.tf", "zscore", "fold")

#backtransform
sm.cv.sp$obs.btf <- btf(sm.cv.sp$obs.tf)
sm.cv.sp$pred.btf <- btf(sm.cv.sp$pred.tf)
sm.cv.sp$resid.btf <- sm.cv.sp$pred.btf - dat_sp$depth

#add run data
sm.cv <- sm.cv.sp@data  %>% 
  mutate( 
    LPI = pred.tf - 1.96 * sqrt(var),
    UPI = pred.tf + 1.96 * sqrt(var),
    obsInInt = obs.tf < UPI & obs.tf > LPI) %>% 
  #select(pred.tf, var, obs.tf, LPI, UPI, obsInInt) %>%
  bind_cols(run_tag) %>% 
  mutate(modeltype = "sm")  %>% 
  arrange(id)
```



```{r}
cat(sep = "", "Spatial model cross-validation metrics (not back-transformed, ", parameters$area_abbr, "_", parameters$rundate,
# mean error, ideally 0:
"):\nmean error = ", mean(sm.cv$resid.tf) %>% round(3), 
# MSPE, ideally small
", MSPE = ", mean(sm.cv$resid.tf^2) %>% round(3),
#Mean square normalized error, ideally close to 1
", mean square norm. error = ", mean(sm.cv$zscore^2) %>% round(3),
# correlation observed and predicted, ideally 1
", \ncor obs&pred = ", cor(sm.cv$obs.tf, sm.cv$pred.tf) %>% round(3),
# correlation predicted and residual, ideally 0
", cor pred&resid = ", cor(sm.cv$pred.tf, sm.cv$resid.tf) %>% round(3),
# RSquared
", R2 = ", rsq(observed = sm.cv$obs.tf, predicted = sm.cv$pred.tf) %>% round(3),
# Adjusted RSquared
", R2 adj = ", rsq.adj(observed = sm.cv$obs.tf, predicted = sm.cv$pred.tf, n.predictors = 3, df.int = 1) %>% round(3)
)
```

```{r}
cat(sep = "", "Spatial model cross-validation metrics (back-transformed, ", parameters$area_abbr, "_", parameters$rundate,
# mean error, ideally 0:
"):\nmean error = ", mean(sm.cv$resid.btf) %>% round(3), 
# MSPE, ideally small
", MSPE = ", mean(sm.cv$resid.btf^2) %>% round(3),
# correlation observed and predicted, ideally 1
", \ncor obs&pred = ", cor(sm.cv$obs.btf, sm.cv$pred.btf) %>% round(3),
# correlation predicted and residual, ideally 0
", cor pred&resid = ", cor(sm.cv$pred.btf, sm.cv$resid.btf) %>% round(3),
# RSquared
", R2 = ", rsq(observed = sm.cv$obs.btf, predicted = sm.cv$pred.btf) %>% round(3),
# Adjusted RSquared
", R2 adj = ", rsq.adj(observed = sm.cv$obs.btf, predicted = sm.cv$pred.btf, n.predictors = 3, df.int = 1) %>% round(3)
)


```

```{r}
bubble(sm.cv.sp, "resid.btf", main = "10-fold CV residuals: spatial model")
```


#### Cross validation of linear model


```{r}
#linear model cv
lm.cv.sp <- krige.cv(formula = cbrt_depth ~ elev + slope, 
                     locations = dat_sp, model = NULL, 
                     nfold=10, verbose = FALSE)
lm.cv.sp@proj4string <- dat_sp@proj4string
lm.cv.sp <- cbind(lm.cv.sp, dat_sp)
lm.cv.sp <- lm.cv.sp[,c("id", "var1.pred", "var1.var", "cbrt_depth", "residual", "zscore", "fold")]


names(lm.cv.sp) <- c("id", "pred.tf", "var", "obs.tf", "resid.tf", "zscore", "fold")

#backtransform
lm.cv.sp$obs.btf <- btf(lm.cv.sp$obs.tf)
lm.cv.sp$pred.btf <- btf(lm.cv.sp$pred.tf)
lm.cv.sp$resid.btf <- lm.cv.sp$pred.btf - dat_sp$depth

#add run data
lm.cv <- lm.cv.sp@data  %>% 
  mutate( 
    LPI = pred.tf - 1.96 * sqrt(var),
    UPI = pred.tf + 1.96 * sqrt(var),
    obsInInt = obs.tf < UPI & obs.tf > LPI) %>% 
  #select(pred.tf, var, obs.tf, LPI, UPI, obsInInt) %>%
  bind_cols(run_tag) %>% 
  mutate(modeltype = "lm")  %>% 
  arrange(id)
```


```{r}
cat(sep = "", "Linear model cross-validation metrics (not back-transformed, ", parameters$area_abbr, "_", parameters$rundate,
# mean error, ideally 0:
"):\nmean error = ", mean(lm.cv$resid.tf) %>% round(3), 
# MSPE, ideally small
", MSPE = ", mean(lm.cv$resid.tf^2) %>% round(3),
#Mean square normalized error, ideally close to 1
", mean square norm. error = ", mean(lm.cv$zscore^2) %>% round(3),
# correlation observed and predicted, ideally 1
", \ncor obs&pred = ", cor(lm.cv$obs.tf, lm.cv$pred.tf) %>% round(3),
# correlation predicted and residual, ideally 0
", cor pred&resid = ", cor(lm.cv$pred.tf, lm.cv$resid.tf) %>% round(3),
# RSquared
", R2 = ", rsq(observed = lm.cv$obs.tf, predicted = lm.cv$pred.tf) %>% round(3),
# Adjusted RSquared
", R2 adj = ", rsq.adj(observed = lm.cv$obs.tf, predicted = lm.cv$pred.tf, n.predictors = 3, df.int = 1) %>% round(3)
)
```

```{r}
cat(sep = "", "Linear model cross-validation metrics (back-transformed, ", parameters$area_abbr, "_", parameters$rundate,
# mean error, ideally 0:
"):\nmean error = ", mean(lm.cv$resid.btf) %>% round(3), 
# MSPE, ideally small
", MSPE = ", mean(lm.cv$resid.btf^2) %>% round(3),
# correlation observed and predicted, ideally 1
", \ncor obs&pred = ", cor(lm.cv.sp$obs.btf, lm.cv$pred.btf) %>% round(3),
# correlation predicted and residual, ideally 0
", cor pred&resid = ", cor(lm.cv$pred.btf, lm.cv$resid.btf) %>% round(3),
# RSquared
", R2 = ", rsq(observed = lm.cv.sp$obs.btf, predicted = lm.cv$pred.btf) %>% round(3),
# Adjusted RSquared
", R2 adj = ", rsq.adj(observed = lm.cv.sp$obs.btf, predicted = lm.cv$pred.btf, n.predictors = 3, df.int = 1) %>% round(3)
)
```

```{r}
bubble(lm.cv.sp, "resid.btf", main = "10-fold CV residuals: linear model")
```

#### Estimate null model  

Linear regression with no spatial component

```{r}
#null model lm
lm.null <- lm(depth ~ elev + slope, dat_sp)
summary(lm.null)

  #save predictions
nullmodel <- data.frame(pred.btf = lm.null$fitted.values, modeltype = as.factor("null"), 
                        id = dat_sp$id,
                        area_abbr = parameters$area_abbr, rundate = parameters$rundate)

cat(sep = "", "Linear null-model metrics (", parameters$area_abbr, "_", parameters$rundate,
# mean error, ideally 0:
"):\nR2 = ", rsq(observed = lm.null$model$depth, predicted = lm.null$fitted.values) %>% round(3),
      ", R2 adj = ", rsq.adj(observed = lm.null$model$depth, predicted = lm.null$fitted.values,
                             n.predictors = 2, df.int = 1) %>% round(3),
      ", RMSE = ", rmse(observed = lm.null$model$depth, predicted = lm.null$fitted.values) %>% round(3), " cm")  

cat("\n\nModel equation\n", model_equation(model = lm.null))
```
#### Estimate best linear model from the literature 

```{r}
# Parry 1
#  lpdepth=Exp(0.875+0.00758*"dtm_metres"-0.0903*"slope_england")-25+(0.5*Exp(0.875+0.00758*"dtm_metres"-0.0903*"slope_england"))

pred.parry <- exp(0.875 + 0.00758 * dat_sp$elev - 0.0903 * dat_sp$slope) - 25 + (0.5 * exp(0.875 + 0.00758 * dat_sp$elev - 0.0903 * dat_sp$slope))

pred.parry <- data.frame(pred.btf = pred.parry, 
                         resid.btf = pred.parry - dat_sp$depth, 
                         modeltype = as.factor("parry"), 
                         id = dat_sp$id, 
                         area_abbr = parameters$area_abbr, 
                         rundate = parameters$rundate) 

cat(sep = "", "Exponential model by Parry, metrics (", parameters$area_abbr, "_", parameters$rundate,
# mean error, ideally 0:
"):\nR2 = ", rsq(observed = dat_sp$depth, predicted = pred.parry$pred.btf) %>% round(3),
      ", R2 adj = ", rsq.adj(observed = dat_sp$depth, predicted = pred.parry$pred.btf,
                             n.predictors = 2, df.int = 1) %>% round(3),
      ", RMSE = ", rmse(observed = dat_sp$depth, predicted = pred.parry$pred.btf) %>% round(3), " cm")

cat("\n\nModel equation\nexp(0.875 + 0.00758 * elev - 0.0903 * slope) - 25 + (0.5 * exp(0.875 + 0.00758 * elev - 0.0903 * slope))")
```

```{r}
#merge cv datasets and backtransform
results.cv <- bind_rows(sm.cv, lm.cv, nullmodel, pred.parry) %>% 
  full_join(dat_sp@data, by = c("id", "area_abbr", "rundate")) %>% 
  mutate_if(is.character, as.factor) %>% 
  dplyr::select(id, area_abbr, rundate, depth:cbrt_depth, everything())
```
### Results summary  


```{r, ft.align="left"}
# summarise backtransformed model metrics
table.metrics <- results.cv %>% 
  group_by(area_abbr, rundate, modeltype) %>% 
  summarise(
    rmse = rmse(observed = depth, predicted = pred.btf) %>% round(3), 
    r2 = rsq(observed = depth, predicted = pred.btf) %>% round(3),
    r2adj = rsq.adj(observed = depth, predicted = pred.btf, n.predictors = 3, df.int = 1) %>% round(3),
    cc = cor(depth, pred.btf),
    coverage = mean(obsInInt), 
    bias = mean(pred.btf - depth), 
    interv = btf(mean(UPI - LPI))) %>% 
  mutate(modeltype = fct_relevel(modeltype, c("sm", "lm", "null", "parry"))) %>%
  arrange(modeltype) %>% 
  mutate_at(vars(rmse, cc, coverage, bias, interv), funs(round, .args = list("digits" = 2))) %>% 
  mutate(summarytext = paste0(modeltype, ": RMSE = ", round(rmse, 2), 
                       "cm, cc = ", round(cc, 2))) %>% 
  ungroup()
  

flextable(table.metrics %>% dplyr::select(modeltype:interv)) %>% 
  set_caption(caption = "Table 2. Performance metrics for spatial and linear models") %>% 
  add_footer_lines(paste(parameters$area_name, parameters$rundate)) %>% 
  autofit()
```


                 


```{r fig.align="left", fig.width=10, message=FALSE, warning=FALSE}
#graph predicted v observed values
model.labels <- table.metrics$summarytext
names(model.labels) <- table.metrics$modeltype

ggplot(results.cv, aes(x = depth, y = pred.btf)) +
  geom_point(aes(colour = modeltype, shape = modeltype), position = position_dodge(width = 2), size = 1.3, alpha = 0.3)+
  geom_abline(slope = 1) +
  coord_equal()+#(ylim = c(-50, 250), xlim = c(-50,250)) +
  scale_colour_discrete(label = model.labels) +
  guides(colour = guide_legend(title = "model type", override.aes = list(alpha = 1, size = 2)), shape = "none") +
  labs(title = "Predicted v observed values", subtitle = paste(parameters$area_abbr, parameters$rundate)) + 
  theme_minimal(base_size = 10)

  
ggsave(filename = paste0("../outputs/predvobs__", 
                         parameters$area_abbr, "_",
                         parameters$rundate, ".png"))
```

```{r}
# export 
write_rds(results.cv, path = paste0("../outputs/results.cv_", 
                                   parameters$area_abbr, "_", 
                                   parameters$rundate, ".rds"))
# export parameters
saveRDS(parameters,  paste0("../data/parameters_", 
                                      parameters$area_abbr, ".rds"))
```

---------------

### Parameters and environment

Run at `r Sys.time()` for **`r params$area_name`** (*`r params$area_abbr`*) with the following parameters: 

```{r, echo=FALSE}
# print list of all parameters
parameters
```
```{r}
sessionInfo()
```



