---
title: "Peat Depth Model: Predict"
params:
  params_fn: 
    input: file
    label: 'Select parameters to import (.rds)'
    value: "../data/parameters_spade.rds"
output:
    html_notebook:
    html_document:
    df_print: paged

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo= TRUE)
```

-------  

Run at `r Sys.time()` for **`r params$area_name`** (*`r params$area_abbr`*) with the following parameters: 

```{r, echo=FALSE}
#import parameters from previous runs
parameters <- readRDS(file = params$params_fn)

# if you need to change any imported parameters, do it here, e.g.: 
  #parameters$existing_parameter <- newvalue
  #parameters$new_parameter <- value

# add new parameters from yaml header

  # automatically defined session variables 
  #set current time and date to append to run log 

# print list of all parameters
parameters
  
#set params for script
par.ori <- par() #save default plotting parameters


```


-------    

## Introduction

This script predicts peat depths from models created in previous scripts.  It outputs:   

*   a raster of predicted depths
*   a raster of prediction variance



```{r}
#load packages
library(tidyverse)#
library(raster)
library(rgdal)
library(sp)
library(sf)
library(elevatr)
library(geoR)
library(gstat)
library(stars)

source("rsquared_funs.R")
source("backtransform.R")
```

```{r}
#pre-set which back-transformation to use

btf <- function(x) {
  backtransform(x = x, tf = parameters$tf)
}
```


## 1. Import previously prepared data

```{r}
#import model and data

# import model
model.geo <- readRDS(parameters$model_fn)

# import observations
sp_depth <- readRDS(parameters$inputs_fn)

# columns which identify the model run
run_tag <- data.frame(area_abbr = rep(parameters$area_abbr, nrow(sp_depth)), rundate = rep(parameters$rundate, nrow(sp_depth)))

# the data used to generate the model
dat_sp <- cbind(sp_depth, 
                parameters$area_abbr, parameters$rundate)
names(dat_sp) <- c(names(sp_depth), "area_abbr", "rundate")
dat_sp$id <- seq(1,nrow(sp_depth)) #add an index

# remove duplicates 
dat_sp <- remove.duplicates(obj = dat_sp)
dat_sf <- st_as_sf(dat_sp)
# re-project
#dat_sp <- sp::spTransform(x = dat_sp, CRSobj = crs(sp_depth))

# import predictors as `stars` objects
elevation_st <- stars::read_stars(parameters$elev_raster_fn)
slope_st <- read_stars(parameters$slope_raster_fn)
 
preds_st <- c(elev = elevation_st, slope = slope_st)
names(preds_st) <- c("elev", "slope")
preds_st <- st_set_crs(x = preds_st, value = st_crs(sp_depth))

#rm(elevation_st, slope_st)
```

```{r}
#check projections are the same
st_crs(preds_st) == st_crs(dat_sf)
```


## Prediction


```{r}
krige.out <- gstat::krige(formula = cbrt_depth ~ elev + slope, 
                   locations = dat_sf,
                   newdata = preds_st,
                   model = model.geo)


#backtransform

krige.out <- krige.out %>% mutate(pred.btf = btf(var1.pred), 
                                  var.btf = btf(var1.var),
                                  LPI = pred.btf - 1.96 * sqrt(var.btf),
                                  UPI = pred.btf + 1.96 * sqrt(var.btf),
                                  interval = UPI - LPI)
```

```{r}
#save to disk

saveRDS(object = krige.out, file = paste0("../outputs/krige.out_", 
                      parameters$area_abbr, "_",
                      parameters$rundate, ".rds"))
write_stars(obj = krige.out, layer = "pred.btf", 
            dsn = paste0("../outputs/krige.pred_", parameters$area_abbr, "_",
                      parameters$rundate, ".tif"))

write_stars(obj = krige.out, layer = "var.btf", 
            dsn = paste0("../outputs/krige.var_", parameters$area_abbr, "_",
                      parameters$rundate, ".tif"))

write_stars(obj = krige.out, layer = "LPI", 
            dsn = paste0("../outputs/krige.LPI_", parameters$area_abbr, "_",
                      parameters$rundate, ".tif"))

write_stars(obj = krige.out, layer = "UPI", 
            dsn = paste0("../outputs/krige.UPI_", parameters$area_abbr, "_",
                      parameters$rundate, ".tif"))

write_stars(obj = krige.out, layer = "interval", 
            dsn = paste0("../outputs/krige.interval_", parameters$area_abbr, "_",
                      parameters$rundate, ".tif"))
```


```{r}
#raster::extract environmental and topographic data for each peat depth measurement
preds.compare <- raster::extract(raster(paste0("../outputs/krige.pred_", parameters$area_abbr, "_",
                      parameters$rundate, ".tif")), coordinates(dat_sp)[,1:2]) 

preds.compare <- data.frame(predictions = preds.compare, observations = dat_sf$depth) %>% 
  mutate(residual = predictions - observations)



cat(sep = "", "Peat depth output metrics for measured locations (", parameters$area_abbr, "_", parameters$rundate, 
    "):\nR2 = ", rsq(observed = preds.compare$observations, predicted = preds.compare$predictions) %>% round(3),
    ", R2 adj = ", rsq.adj(observed = preds.compare$observations, predicted = preds.compare$predictions, n.predictors = 2, df.int = 1) %>% round(3),
    ", RMSE = ", rmse(observed = preds.compare$observations, predicted = preds.compare$predictions) %>% round(3), " cm", 
    "\n(note this is not a metric for un-measured locations)")

ggplot(data = preds.compare, aes(x = observations, y = predictions)) + 
  geom_point() + geom_abline(slope = 1) + ggpubr::theme_pubr()

ggplot(data = preds.compare, aes(x = residual)) + 
  geom_histogram() + ggpubr::theme_pubr()
```




